#!/bin/bash

# config directory
CONFIG_DIR=~/.config/rdcli

# login file
LOGIN_FILE=$CONFIG_DIR"/rdcli.login"

# cookie file
COOKIE=$CONFIG_DIR"/cookies.txt"

# directory to store rdcli's temp files
TMP_DIR=/tmp/rdcli

LOGGED=false

# Print rdcli usage information
usage() {
    echo "Usage: ./rdcli LINK"
    echo "Where LINK can be a URL to the file you want to dowload or a file containing several links."
    echo "Example: ./rdcli http://host.com/myFile.zip"
    echo "Example: ./rdcli urls.txt"
}

# Ask for user's login and password
ask_login() {
    echo "What is your Real-Debrid username ?"
    read LOGIN
    echo "What is your Real-Debrid password ? (will not be displayed)"
    read -s PASSWORD

    PASSWORD=`echo -n $PASSWORD | md5sum | tr -d " -"`

    echo $LOGIN":"$PASSWORD > $LOGIN_FILE 
}

# Log into real-debrid.com and record a cookie so we 
# don't need to login back again for multiple downloads
login() {

    # if a cookie already exists and it's not expired
    if [ -r $COOKIE ] 
        then
        echo "OK"
    else
        local TMP_RESP=$TMP_DIR"/"rdcli-login-response.json
        
        wget -q --save-cookies $COOKIE --keep-session-cookies -O $TMP_RESP \
        "http://www.real-debrid.com/ajax/login.php?user=$LOGIN&pass=$PASSWORD"
        
        local RESULT=`cat $TMP_RESP | tr -d "{}\"" | cut -d, -f2 | cut -d: -f2`
        if [ $RESULT == "OK" ]
            then
            LOGGED=true
        fi

        rm $TMP_RESP
    fi
}

unrestrict() {
    local TMP_RESP=$TMP_DIR"/"rdcli-unrestrict-response.json

    wget -q --load-cookies $COOKIE -O $TMP_RESP \
    "http://www.real-debrid.com/ajax/unrestrict.php?link=$1"

    local RESULT=`grep -o "_link\":\"\(.*\),\"l" $TMP_RESP | cut -d "\"" -f3`

    echo $RESULT | sed 's/\\//g'

    rm $TMP_RESP
}

# Download a file
download() {
    wget $1
}

# main programm
main() {
    mkdir -p $CONFIG_DIR

    if [ $# -lt 1 ]
    	then
        echo "You must provide an URL"
        usage
        exit 1
    else
        # check for login info
        if [ ! -r $LOGIN_FILE -a ! -s $LOGIN_FILE ]
        	then
            ask_login
        fi

        # retrieve login info
        if [ -z $LOGIN -o -z $PASSWORD ]
        	then
            LOGIN=`cut -d: -f1 $LOGIN_FILE`
            PASSWORD=`cut -d: -f2 $LOGIN_FILE`
        fi

        mkdir -p $TMP_DIR

        if [ ! -r $COOKIE ]
            then
            echo "no existing cookie, login in..."
            login
        elif [ `tail -1 $COOKIE | cut -f5` -gt `date +%s` ] 
            then
            echo "valid cookie"
            LOGGED=true
        else
            echo "previous cookie expired"
            login
        fi

        if [ LOGGED ]
        	then  
            echo "login OK"

            # if the last arguments is a file, 
            if [ -r "${!#}" ] 
            	then
                echo "multiple downloads" 

                ORIGINAL_LINKS_FILE=${!#}
                UNRESTRICTED_LINKS_FILE=$TMP_DIR"/rdcli-unrestricted"
                echo -n "" > $UNRESTRICTED_LINKS_FILE
                
                for LINK in `cat $ORIGINAL_LINKS_FILE`
                    do
                    echo -n "unrestricting $LINK"
                    UNRESTRICTED=`unrestrict $LINK`

                    if [ ${#UNRESTRICTED} -gt 1 ]
                        then
                        echo " -> $UNRESTRICTED"
                        echo $UNRESTRICTED >> $UNRESTRICTED_LINKS_FILE
                    else
                        echo " -> WARNING: Unrestriction failed, this file will not be downloaded."
                    fi
                done

                wget -i $UNRESTRICTED_LINKS_FILE
                rm $UNRESTRICTED_LINKS_FILE
            else
                echo "single download"
                echo "unrestricting $1"
                wget `unrestrict $1`
            fi
        else
            echo "Login failed"
        fi

        rm -rf $TMP_DIR

        echo "End"
    fi
}

main "$@"
exit 0