#!/bin/bash

if [ -n "$1" ]
then
    TMP="/tmp/rdsd.html"
    wget -q $1 -O $TMP
    URL=`grep -m 1 -o "http://s[0-9]*\.real-debrid\.com/dl/[a-zA-Z0-9]*/video\.flv" $TMP`
    
    if [ -n "$URL" ] 
    then
        echo "URL: "$URL

        if [ -n "$2" ]
        then
            FILE=$2
        else
            FILE=`grep -o "<meta name=\"og:title\" content=\".*\" />" $TMP | cut -d\" -f4`
        fi

        FILE=$FILE".flv"
        echo "Saving as "$FILE

        wget $URL -O "$FILE"
        echo "Download complete!"
        rm $TMP
    else
        echo "No video found for \""$1"\", exiting."
    fi
else
    echo "You must provide an URL"
fi

exit 0