#!/bin/bash

if [ -n "$1" ] 
then
    URL=`curl -s $1 | grep -m 1 "http://s[0-9]*\.real-debrid\.com/dl/[a-zA-Z0-9]*/video\.flv" | cut -d\' -f2`;
    
    if [ -n "$URL" ] 
   	then
    	echo "URL: "$URL;

   		if [ -n "$2" ]
   		then
   			FILE=$2;
   		else
   			FILE=`date +%Y.%m.%d-%H:%M:%S`"-video"
   		fi
   		FILE=FILE".flv";
   		echo "Saving as "$FILE;

   		wget $URL -O $FILE;
   		echo "Download complete!"
   	else
   		echo "No video found for \""$1"\", exiting.";
    fi
else
    echo "You must provide an URL";
fi

exit 0;